### ISSUE TITLE
performance of the slice iterator

### ISSUE THREAD

**Issue by inv2004** [lumol-org/soa-derive#14]
Looks like performance of the iterators is ~x3 times slower than std .zip or izip!
izip!: 4.9sec , CheeseSlice: 15.9 sec

Regards,

**Comment by Luthaf** [comment]
What code are you using for your benchmark ?

I think this might be related to missing implementation of `Iterator::size_hint` and other helper methods in https://github.com/lumol-org/soa-derive/blob/bb9d45a726e853cd61f4a710c437433433cacf77/soa-derive-internal/src/iter.rs#L39-L51

Generally speaking, I am certain there are quite a few performances optimizations that are possible to improve this crate.

**Comment by inv2004** [comment]
Please find I just created:

I did 4 fields => more fields => slower.
https://github.com/inv2004/soa_iter_bench

For me its a bit strange that test_new2 is the fastest and test_new is slow, because looks like prev day I see that test_new was the fastest and test_new2 x1.5 slower.

```
running 5 tests
test test_izip ... bench:     517,470 ns/iter (+/- 31,921)
test test_new  ... bench:   1,208,318 ns/iter (+/- 38,745)
test test_new2 ... bench:     494,725 ns/iter (+/- 29,403)
test test_old  ... bench:   1,203,817 ns/iter (+/- 25,856)
test test_zip  ... bench:     509,945 ns/iter (+/- 26,682)
```

**Comment by inv2004** [comment]
size_hint did not change anything: https://github.com/inv2004/soa_iter_bench/commit/e594312f104a5425440c2a9fc9fffa79a123265e
```
running 5 tests
test test_izip ... bench:     106,009 ns/iter (+/- 7,491)
test test_new  ... bench:     199,861 ns/iter (+/- 13,772)
test test_new2 ... bench:     106,520 ns/iter (+/- 5,779)
test test_old  ... bench:     269,461 ns/iter (+/- 16,255)
test test_zip  ... bench:     105,314 ns/iter (+/- 4,614)
```

**Comment by Luthaf** [comment]
Oh, OK, I think I understand the issue better! The main problem here might be that we have to create new SRef<'a> at each step of the iteration, and then dereference it.

You should be able to use the [`soa_zip!`](https://docs.rs/soa_derive/0.6.1/soa_derive/macro.soa_zip.html) macro instead of `izip!` and get at least the same performance (both macro expand to basically the same code)

**Comment by inv2004** [comment]
Hm. I am not so sure that the problem is in creation of CheeseRef, because test_izip and test test_zip creates CheeseRef too: https://github.com/inv2004/soa_iter_bench/blob/master/src/main.rs#L228

```
test test_zip             ... bench:     523,696 ns/iter (+/- 16,403)
test test_zip_without_ref ... bench:     542,164 ns/iter (+/- 58,219)
```

**Comment by Luthaf** [comment]
What does this gives with `soa_zip!`?

**Comment by inv2004** [comment]
Please find some update.

I created new test from test_old and used construction from core::iter::Zip source code: https://github.com/inv2004/soa_iter_bench/blob/d7a30016fcee702331d05ad24a17addb43b806e7/src/main.rs#L101

and now it looks like it improved situation a lot:
```
running 10 tests
test test_new2_rev_test ... ignored
test test_izip            ... bench:     550,991 ns/iter (+/- 34,369)
test test_new             ... bench:   1,242,180 ns/iter (+/- 31,991)
test test_new2            ... bench:     628,175 ns/iter (+/- 27,861)
test test_new2_rev        ... bench:     702,763 ns/iter (+/- 29,718)
test test_old             ... bench:   1,247,024 ns/iter (+/- 20,131)
**test test_old2            ... bench:     622,488 ns/iter (+/- 18,691)**
test test_zip             ... bench:     549,055 ns/iter (+/- 26,092)
test test_zip_rev         ... bench:     570,239 ns/iter (+/- 27,660)
test test_zip_without_ref ... bench:     554,853 ns/iter (+/- 57,848)
```

**Comment by Luthaf** [comment]
Wow, this looks good! And should not be too hard to implement also.

---

Just to know, it sound like you want to abstract over Slice/Vec in your use case, why? 

One possibility to do so would be to have an `AsSlice` trait that convert everything to a slice, and then work from here. Both XXXVec and XXXSliceMut have a `slice()` method that can be used for this.

**Comment by inv2004** [comment]
If You would like to implement it, please do not forget about std::iter::DoubleEndedIterator, which is useful for many cases.

I have a different structs, for example S1, S2, S3, S3 with different fields, all of them derive SoA. because vectorized structure calculations are much master + structure of the data is more contant: vec of numbers is easier to use than vectors of structs with numbers.

then I implemented fn calc (for ref) to make some comp with S1,2,3,4 and different fields. Now, with Iterators I can easy write universal function without working with fields:
```
let sl = (S1Slice or SVec):: new(...);
for x in &sl { x.calc() } .
```

Unfortunately test_old2 is still slower than test_zip.

**Comment by inv2004** [comment]
I feel like I am a bit annoying, but please find new update:

```
running 10 tests
test test_new2_rev_test ... ignored
test test_izip            ... bench:     505,946 ns/iter (+/- 9,750)
test test_new             ... bench:     501,313 ns/iter (+/- 38,063)
test test_new2            ... bench:     589,285 ns/iter (+/- 45,108)
test test_new2_rev        ... bench:     653,283 ns/iter (+/- 19,451)
test test_old             ... bench:   1,197,755 ns/iter (+/- 13,299)
test test_old2            ... bench:     570,729 ns/iter (+/- 36,173)
test test_zip             ... bench:     504,843 ns/iter (+/- 31,671)
test test_zip_rev         ... bench:     533,405 ns/iter (+/- 43,096)
test test_zip_without_ref ... bench:     509,646 ns/iter (+/- 35,153)
```

test_new implementation has time exactly like test_zip. I suppose iter::Zip makes some optimizations, that is why it is the fastest.

Unfortunately this PR will not be so easy like test_old2, but I will try:
https://github.com/inv2004/soa_iter_bench/blob/93dd8d2403c6ca16063545c72b7ee1c34c16cdf5/src/main.rs#L145

**Comment by Luthaf** [comment]
Thank you very much for your investigation here!

**Comment by inv2004** [comment]
Thanks to You.

**Comment by inv2004** [comment]
Please do not publish, because looks like DoubleEndedIterator and .rev() have performance problems. Do not know why at the moment.
