### ISSUE TITLE
Update versions of `syn` and `quote`

### ISSUE THREAD

**Issue by rodya-mirov** [lumol-org/soa-derive#20]
Currently I have some issues where I'm pulling in old versions of `syn` and `quote` due to using this as a dependency, and it's hurting build times.  Probably we could unpin those versions entirely and let consumers of the library decide?

**Comment by Luthaf** [comment]
Hi, I already had updated this to use the 1.0 version of syn and quote, but forgot to publish the update. I just released 0.8.1 which should solve this.

Let me know if this works for you!

**Comment by Luthaf** [comment]
Closing since this should be fixed. Please re-open if it is not the case.

**Comment by rodya-mirov** [comment]
Hi @Luthaf sorry I didn't get back to you earlier! I really appreciate you doing this (so quickly!). We immediately upgraded our package, and our production build is now noticeably faster.

Thanks again.
