### ISSUE TITLE
Use trait to link the origin struct to generated soa struct

### ISSUE THREAD

**Issue by mikialex** [lumol-org/soa-derive#24]
We can create type connection between the origin struct to generated struct by trait like bellow:

```rust
pub trait StructOfArraySource {
  type ArrayType
}

// this part generated in marco
impl StructOfArraySource for Cheese {
  type ArrayType = CheeseVec
}
```

After this, we can use `<Cheese as StructOfArraySource>::ArrayType` instead of hard code name `CheeseVec`.

Type connection is important in generics programing. If I have type T, some container is soa derived and I need describe that container type by T. We can use `<T as StructOfArraySource>::ArrayType`. It seems the only way.

**Comment by Luthaf** [comment]
That sounds like a good idea, what do you think of `StructOfArray::Type` as a shorter name?

**Comment by mikialex** [comment]
yes it's a better name

**Comment by Luthaf** [comment]
I don't have much time to dedicate to this projects nowadays, but I'm happy to take a PR implementing & documenting this! The trait itself could live in the `soa_derive` crate; and the implementation in `soa_derive_internals`
