### ISSUE TITLE
Add access methods

### ISSUE THREAD

**Issue by copying** [lumol-org/soa-derive#27]
Add the methods [`get`](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.get), [`get_mut`](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.get_mut), [`get_unchecked`](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.get_unchecked), and [`get_unchecked_mut`](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.get_unchecked_mut) of  `Vec` to the generated SoA.

Right now it's not possible implement the trait `Index` and `IndexMut`. This issue would add a way to access the elements in a way that also works for `Vec`. This would also make accessing the underlying `Vec` not required.
```rust
// Before
let value = vec.field[1];

// After
let value = vec.get(1)?.field; // vec could be an ExampleVec or a Vec<Example>
```
And we might get a reference (which we couldn't do before):
```rust
let reference = vec.get(2)?;
```
Also would support ranges:
```rust
let slice = vec.get(0..5)?;
```
And we should probably add ranges to our custom slice so it's possible to get an smaller slice from a slice.

To do so, it would make sense to make a trait similar to [SliceIndex](https://doc.rust-lang.org/std/slice/trait.SliceIndex.html) but changing the output to not require returning a reference (so we can use our struct of references).

**Comment by copying** [comment]
Really useful for the issue #19 where you don't have underlying vectors, so this gives a common interface for both versions and `Vec`.

**Comment by Luthaf** [comment]
Sounds good to me!

**Comment by copying** [comment]
Also adding `index` and `index_mut` because `get` returns an `Option<T>`. It will keep the same behaviour as using the index operator:
```rust
// vec: Vec<Example>
vec[0];

// soa: ExampleVec
soa.index(0);
```
Should behave the same (even when it fails) and work with ranges :)
