### ISSUE TITLE
How do you go from `MyTypeRef` to `MyType` ?

### ISSUE THREAD

**Issue by A1Liu** [lumol-org/soa-derive#54]
Is there a method for "dereferencing" the `MyTypeRef` and getting the entire object by-value? I'm having trouble finding it in source or the docs.

The use-case I have is copying a `MyTypeVec` into another SOA vec while filtering out some of the values.

I apologize if I'm missing something obvious.

**Comment by Luthaf** [comment]
Looks like we need a `ToOwned` implementation for the references. I'll have a look!

**Comment by A1Liu** [comment]
Wow, thank you so much! Would this new feature go in `0.13.0`, along with the sorting methods?

**Comment by Luthaf** [comment]
I'll do a bit more cleanup, and I'll try to release 0.13.0 before the end of the week

**Comment by A1Liu** [comment]
OK thank you! Please let me know if there's anything I can do to help with testing or release.

**Comment by Luthaf** [comment]
0.13 is now released, please let me know if it works for you!
