### ISSUE TITLE
How to set #[pyclass] attribute for soa-derived struct?

### ISSUE THREAD

**Issue by cuihantao** [lumol-org/soa-derive#59]
Thank you for the great efforts in `soa_derive`! I'm still new to Rust, and I wonder how `#[pyclass]` can be applied to an soa-derived class?

The following will not work as `#[pyclass]` is applied to `Element`, not `ElementVec`.
```
#[pyclass]
#[derive(StructOfArray, Debug)]
pub struct Element {
   num: f64,
}
```

**Comment by Luthaf** [comment]
You should use the `soa_attr` attribute:

```
#[derive(StructOfArray, Debug)]
#[soa_attr(Vec, pyclass)]
pub struct Element {
   num: f64,
}
```

The first argument to soa_attr indicates to which of the generated struct the attribute should be applied (`Vec`, `Slice`, `Ref`, `Ptr`, or the `XXXMut` version of the last three)

**Comment by cuihantao** [comment]
Thank you very much! Now I see what that section means in the README.
