### ISSUE TITLE
Is it possible to use the crate with lifetime parameters?

### ISSUE THREAD

**Issue by inv2004** [lumol-org/soa-derive#9]
Hello, I have struct which has lifetime parameters:
```
#[derive(Debug, StructOfArray)]
struct Ind2<'a> {
    ts: &'a str,
    sma_short: f32,
    sma_long: f32,
    sma_raise: f32,
    sma_fall: f32,
}
```
Error is:
```
error[E0261]: use of undeclared lifetime name `'a`
 --> src/file.rs:1:17
  |
1 | #[derive(Debug, StructOfArray)]
  |                 ^^^^^^^^^^^^^ undeclared lifetime

error[E0106]: missing lifetime specifier
 --> src/file.rs:1:17
  |
1 | #[derive(Debug, StructOfArray)]
  |                 ^^^^^^^^^^^^^ expected lifetime parameter

error: aborting due to 2 previous errors
```

Question: Is it possible to apply the derive for struct with lifetimes?

Thank you,

**Comment by Luthaf** [comment]
Hi ! 

Currently, this is not possible. The code does not insert lifetime parameters in the struct definition (resulting in the error you see). You can use owned value (`String`) without any issue though.

References could be supported with more code, but there are a few design questions to consider. I don't have much time to work on this now, but I'll be happy to review pull-requests.

**Comment by inv2004** [comment]
Thank you.

**Comment by FeistyKit** [comment]
Has this been fixed/patched since then?

**Comment by Luthaf** [comment]
No, this crate did not change much since 2018 =). My stance is still the same:

> References could be supported with more code, but there are a few design questions to consider. I don't have much time to work on this now, but I'll be happy to review pull-requests.
